/*
 * ultrasonic.c
 *
 *  Created on: Oct 15, 2023
 *      Author: omars
 */
#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include <util/delay.h>

static volatile uint16 g_travellingTime=0; /*High time of ICU*/
static volatile uint8 g_counter=0; /*Edges counter*/

/*
 * Description:
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void){
	g_counter++;
	if(g_counter==1){
		ICU_clearTimerValue();
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_counter==2){
		g_travellingTime=ICU_getInputCaptureValue();
		ICU_setEdgeDetectionType(RAISING);

	}
	else{
		g_counter=0;
	}
}
/*
 * Description:
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the GPIO driver.
 *
 */
void Ultrasonic_init(void){
	ICU_ConfigType config={F_CPU_8,RAISING};
	ICU_init(&config);
	ICU_setCallBack(Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection(TR_PORT_ID,TR_PIN_ID,PIN_OUTPUT);
}

/*
 * Description:
 * Send the Trigger pulse to the ultrasonic
 */
void Ultrasonic_Trigger(void){
	GPIO_writePin(TR_PORT_ID,TR_PIN_ID,HIGH);
	_delay_us(12);
	GPIO_writePin(TR_PORT_ID,TR_PIN_ID,LOW);
}

/*
 * Description:
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void){
	uint16 distance=0;
	Ultrasonic_Trigger();
	/*wait until the calculations finished*/
	while(g_counter!=2); /*polling*/
	distance=(uint16)(g_travellingTime/58.8);
	return distance;
}
