/*
 * ultrasonic.h
 *
 *  Created on: Oct 15, 2023
 *      Author: omars
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_


/*******************************************Definitions**************************************/
#define TR_PORT_ID PORTB_ID
#define TR_PIN_ID PIN5_ID

#include "Standerd_Types_OS.h"

/******************************************Functions Prototype*******************************/
/*
 * Description:
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

/*
 * Description:
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the GPIO driver.
 *
 */
void Ultrasonic_init(void);

/*
 * Description:
 * Send the Trigger pulse to the ultrasonic
 */
void Ultrasonic_Trigger(void);

/*
 * Description:
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);

#endif /* ULTRASONIC_H_ */
